name: Build

on: 
  push:
    branches:
      - "modtek"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Build
      run: |
        dotnet build --configuration Release ./Harmony/Harmony.csproj
        dotnet pack --configuration Release ./Harmony/Harmony.csproj
    - name: Release Latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete latest --cleanup-tag || true
        git tag -d latest || true
        git push --delete origin refs/tags/latest || true
        git tag latest
        git push --force origin refs/tags/latest
        gh release create latest Harmony/bin/Release/HarmonyX*.nupkg Harmony/bin/Release/net452/0Harmony.dll \
          --generate-notes \
          --title "Latest (unstable)" \
          --verify-tag \
          --prerelease
